version: "3"

services:
  yii2-app:
    image: yateshingale/yii2-app:latest
    deploy:
      replicas: 1
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

