name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest ./docker
        docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
          docker service update --image ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest yii2app_yii2-app || \
          docker stack deploy -c /home/ubuntu/docker-compose.yml yii2app

